module.exports = {
    //Main Codes
mainCodes: [
    {"key": "01", "value": "Jackets"},
    {"key": "02", "value": "Suits"},
    {"key": "03", "value": "Shirts"},
    {"key": "04", "value": "Trousers"},
    {"key": "05", "value": "Belts"},
    {"key": "06", "value": "Socks"},
    {"key": "07", "value": "Underwear"},
    {"key": "08", "value": "Shoes"},
    {"key": "09", "value": "Jerseys"},
    {"key": "10", "value": "Casual Jackets"},
],

//Sub Codes
shirtCodes: [
    {"key": "01", "value": "LS Lounge Shirt"},
    {"key": "02", "value": "SS Plain"},
    {"key": "03", "value": "SS Check"},
    {"key": "04", "value": "SS Stripe"},
    {"key": "05", "value": "SS Golfer"},
    {"key": "06", "value": "SS T-Shirt"},
    {"key": "07", "value": "LS Check"},
    {"key": "08", "value": "LS Stripe"},
],

trouserCodes: [
    {"key": "01", "value": "Pleated Chinos"},
    {"key": "02", "value": "Pleated Denims"},
    {"key": "03", "value": "Five Pocket Denims"},
    {"key": "04", "value": "Cargo Trousers"},
    {"key": "05", "value": "Formal Trousers"},
    {"key": "06", "value": "Elasticated Shorts"},
    {"key": "07", "value": "Flat Front Chino"}
],

beltCodes: [
    {"key": "01", "value": "Formal Belt"},
    {"key": "02", "value": "Casual Belt"}
],

sockCodes: [
    {"key": "01", "value": "Anklets"},
    {"key": "02", "value": "Sport Socks"}
],

underwearCodes: [
    {"key": "01", "value": "Skants"},
    {"key": "02", "value": "Pouch Trunks"},
    {"key": "03", "value": "Woven Boxers"},
    {"key": "04", "value": "Vests"}
],

jerseyCodes: [
    {"key": "01", "value": "V-Neck Jersey"},
    {"key": "02", "value": "Round Neck Jersey"},
    {"key": "03", "value": "Pull Over Jersey"},
    {"key": "04", "value": "Jersey Golfer"}
],

jacketCodes: [
    {"key": "01", "value": "Puffer Jacket"},
    {"key": "02", "value": "Fleece Jacket"},
    {"key": "03", "value": "Hoodie Jacket"},
],

//Color Codes
colourCodes: [
    {"key": "01", "value": "White"},
    {"key": "02", "value": "Beige"},
    {"key": "03", "value": "Taupe"},
    {"key": "04", "value": "Bark"},
    {"key": "05", "value": "Brown"},
    {"key": "06", "value": "Grey"},
    {"key": "07", "value": "Charcoal"},
    {"key": "08", "value": "Black"},
    {"key": "09", "value": "Blue"},
    {"key": "10", "value": "Teal"},
    {"key": "11", "value": "Royal"},
    {"key": "12", "value": "Navy"},
    {"key": "13", "value": "Olive"},
    {"key": "14", "value": "Red"},
    {"key": "15", "value": "Green"},
    {"key": "16", "value": "Brick"},
    {"key": "17", "value": "Purple"},
    {"key": "18", "value": "Orange"},
    {"key": "19", "value": "Yellow"},
    {"key": "20", "value": "Banana"},
    {"key": "21", "value": "Oatmeal"},
    {"key": "22", "value": "Khaki"},
    {"key": "23", "value": "Smoke"},
    {"key": "24", "value": "Pacific"},
    {"key": "25", "value": "Burgundy"},
    {"key": "26", "value": "Assorted"},
    {"key": "27", "value": "White-Blue"},
    {"key": "28", "value": "White-Black"},
    {"key": "29", "value": "White-Navy"},
    {"key": "30", "value": "White-Khaki"},
    {"key": "31", "value": "Grey-Black"},
    {"key": "32", "value": "Aqua"},
    {"key": "33", "value": "Combat"},
    {"key": "34", "value": "Red-Black"},
    {"key": "35", "value": "Red-Blue"},
    {"key": "36", "value": "Denim-White"},
    {"key": "37", "value": "Navy-Melange"},
    {"key": "38", "value": "Grey-Navy"},
    {"key": "39", "value": "Coffee Bean"},
    {"key": "40", "value": "Grey-White"},
    {"key": "41", "value": "Navy-Pale Blue"},
    {"key": "42", "value": "Black-Grey"},
    {"key": "43", "value": "Rust"},
    {"key": "44", "value": "Silver-Grey"},
    {"key": "45", "value": "Blue-Navy"},
    {"key": "46", "value": "Blue-Black"},
    {"key": "47", "value": "Blue-White"},
    {"key": "48", "value": "Blue Wash"},
    {"key": "49", "value": "Navy"},
    {"key": "50", "value": "Blue-Red"},
    {"key": "51", "value": "Brick-Navy"},
    {"key": "52", "value": "Indigo"},
    {"key": "53", "value": "Navy-White"},
    {"key": "54", "value": "Olive-Blue"},
    {"key": "55", "value": "Charcoal Mel"},
    {"key": "56", "value": "Stripe-Grey"},
    {"key": "57", "value": "Jungle"},
    {"key": "58", "value": "Blue Mel"},
    {"key": "59", "value": "Offwhite-Oxyfire"},
    {"key": "60", "value": "Wine"},
    {"key": "61", "value": "Navy-Stone"},
    {"key": "62", "value": "Navy-Royal"},
    {"key": "63", "value": "Teal-Camel"},
    {"key": "64", "value": "Blue-Wine"},
    {"key": "65", "value": "Wine Jeep"},
    {"key": "66", "value": "Navy-Wine"},
    {"key": "67", "value": "Black Jeep"},
    {"key": "68", "value": "Navy-Wine"},
    {"key": "69", "value": "Olive-Black"},
    {"key": "79", "value": "Camel"},
    {"key": "80", "value": "Red-Navy"},
    {"key": "81", "value": "Navy-Red"},
    {"key": "82", "value": "Green-Blue"},
    {"key": "83", "value": "Charcoal Jeep"},
],

supplierCodes: [
    {"key": "01", "value": "Allwear"},
    {"key": "02", "value": "Ashby Wholesalers"},
    {"key": "03", "value": "Ayezed"},
    {"key": "04", "value": "Bolton"},
    {"key": "05", "value": "Cape Mohair"},
    {"key": "06", "value": "Collies Clothing"},
    {"key": "07", "value": "Ninian & Lester"},
    {"key": "08", "value": "Dale Footwear"},
    {"key": "09", "value": "Derlee"},
    {"key": "10", "value": "Distinctive Choice"},
    {"key": "11", "value": "Falke Socks"},
    {"key": "12", "value": "Faulke & Co"},
    {"key": "13", "value": "Heriswell"},
    {"key": "14", "value": "Monatic"},
    {"key": "15", "value": "Kaytex Belts"},
    {"key": "16", "value": "Kenasco Shirts"},
    {"key": "17", "value": "KMP Footwear"},
    {"key": "18", "value": "Medicus"},
    {"key": "19", "value": "Jeep"},
    {"key": "20", "value": "Kubwa"},
    {"key": "21", "value": "Promotion"},
    {"key": "22", "value": "Roma Manufacturing"},
    {"key": "23", "value": "Sector Apparel"},
    {"key": "24", "value": "Sterling"},
    {"key": "25", "value": "T-Shirt Manufacturers"},
    {"key": "26", "value": "Tappo"}
],

detailCodes: [
    {"key": "00", "value": "N/A"},
    {"key": "01", "value": "Poly Cotton"},
    {"key": "02", "value": "Cotton"},
    {"key": "03", "value": "3-Pack"},
    {"key": "04", "value": "2-Pack"},
    {"key": "05", "value": "1-Pack"},
    {"key": "06", "value": "Cusion Sole"},
    {"key": "07", "value": "Sport"},
    {"key": "08", "value": "Plain"},
    {"key": "09", "value": "Stitched"},
    {"key": "10", "value": "Pure Cotton"},
    {"key": "11", "value": "100% Cotton"},
    {"key": "12", "value": "60 Pol / 40 Cot"},
    {"key": "13", "value": "100% Cotton"},
    {"key": "14", "value": "100% Cotton"},
    {"key": "15", "value": "65 Pol / 35 Cot"},
    {"key": "16", "value": "65 Pol / 35 Cot"},
    {"key": "17", "value": "Zip Through"},
    {"key": "18", "value": "Nylon"},
    {"key": "19", "value": "Nylon/Knit"},
    {"key": "20", "value": "Acrylic Blend"},
    {"key": "21", "value": "Cotton"}
]
}
